======================================== 
Start time: 2025/05/06 周二 21:40:51.28 
Using conda environment: pytorch_gpu 
Starting Python script execution... 
Traceback (most recent call last):
  File "C:\Users\ZY\Desktop\Forecaster\scripts\task_evaluate.py", line 24, in <module>
    Evaluate_Task.execute_eva() # 依据task_id自动选择类方法创建数据文件
  File "C:\Users\ZY\Desktop\Forecaster\scripts\..\src\model_evaluator\evaluate_src.py", line 93, in execute_eva
    return task_mapping[task_id]()
  File "C:\Users\ZY\Desktop\Forecaster\scripts\..\src\model_evaluator\evaluate_src.py", line 65, in eva_task1
    model_dic[station_id] = model_class(**model_hyperpara)  # 实例化模型
TypeError: User_Model.__init__() got an unexpected keyword argument 'batch_size'
 
End time: 2025/05/06 周二 21:40:55.59 
Script execution completed 
