======================================== 
Start time: 2025/04/28 周一 21:43:38.77 
Using conda environment: pytorch_gpu 
Starting Python script execution... 
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\pytorch_gpu\lib\pickle.py", line 1245, in load_persid
    pid = self.readline()[:-1].decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0x80 in position 127: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\ZY\Desktop\Forecaster\scripts\task_evaluate.py", line 24, in <module>
    Evaluate_Task.execute_eva() # 依据task_id自动选择类方法创建数据文件
  File "C:\Users\ZY\Desktop\Forecaster\scripts\..\src\model_evaluator\evaluate_src.py", line 55, in execute_eva
    return task_mapping[task_id]()
  File "C:\Users\ZY\Desktop\Forecaster\scripts\..\src\model_evaluator\evaluate_src.py", line 33, in eva_task1
    pth_dic[station_id] = joblib.load('../data/user_data/{}/upload_data/model_para_{}_{}_{}_{}.pth'.format(self.user_id, station_id, self.user_id, self.task_id, self.job_number))
  File "C:\ProgramData\Anaconda3\envs\pytorch_gpu\lib\site-packages\joblib\numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "C:\ProgramData\Anaconda3\envs\pytorch_gpu\lib\site-packages\joblib\numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "C:\ProgramData\Anaconda3\envs\pytorch_gpu\lib\pickle.py", line 1213, in load
    dispatch[key[0]](self)
  File "C:\ProgramData\Anaconda3\envs\pytorch_gpu\lib\pickle.py", line 1247, in load_persid
    raise UnpicklingError(
_pickle.UnpicklingError: persistent IDs in protocol 0 must be ASCII strings
 
End time: 2025/04/28 周一 21:43:40.41 
Script execution completed 
